name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK with built-in Maven caching
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven   # ✅ replaces separate cache step

      # 3️⃣ Install dependencies & build (skip tests here)
      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./

      # 4️⃣ Run tests
      - name: Run Unit Tests
        run: mvn test
        working-directory: ./

      # 5️⃣ SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 6️⃣ Package distributable (JAR)
      - name: Package Application
        run: mvn package -DskipTests
        working-directory: ./

      # 7️⃣ Upload artifact (JAR, WAR, ZIP, etc.)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: distributable
          path: target/*.jar
